apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-zqpc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-zqpc
    app.kubernetes.io/part-of: tkrw-pr712-0075-0062-app
  name: devfile-sample-zqpc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-zqpc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-zqpc
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0062-tenant/tkrw-pr712-0075-0062-app/devfile-sample-zqpc@sha256:bb773a2a90cc8501b6f3a91eecffe5e871ed0c93bb0ca71a8ee78efac09071bb
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
